import { Country } from '@interfaces/country';

export function normalizeCountry(apiCountry: any): Country {
  return {
    name: {
      common: apiCountry.name?.common ?? '',
      official: apiCountry.name?.official ?? '',
      nativeName: apiCountry.name?.nativeName ?? {},
    },
    tld: apiCountry.tld,
    cca2: apiCountry.cca2,
    ccn3: apiCountry.ccn3,
    cioc: apiCountry.cioc,
    independent: apiCountry.independent ?? false,
    status: apiCountry.status,
    unMember: apiCountry.unMember,
    currencies: apiCountry.currencies ?? {},
    idd: apiCountry.idd ?? { root: '', suffixes: [] },
    capital: apiCountry.capital ?? [],
    altSpellings: apiCountry.altSpellings ?? [],
    region: apiCountry.region,
    subregion: apiCountry.subregion,
    languages: apiCountry.languages ?? {},
    latlng: apiCountry.latlng ?? [],
    landlocked: apiCountry.landlocked ?? false,
    borders: apiCountry.borders ?? [],
    area: apiCountry.area,
    demonyms: apiCountry.demonyms ?? { eng: { f: '', m: '' }, fra: { f: '', m: '' } },
    cca3: apiCountry.cca3,
    translations: apiCountry.translations ?? {},
    flag: apiCountry.flag ?? '',
    maps: apiCountry.maps ?? { googleMaps: '', openStreetMaps: '' },
    population: apiCountry.population,
    gini: apiCountry.gini ?? {},
    fifa: apiCountry.fifa,
    car: apiCountry.car ?? { signs: [], side: '' },
    timezones: apiCountry.timezones ?? [],
    continents: apiCountry.continents ?? [],
    flags: apiCountry.flags ?? { png: '', svg: '', alt: '' },
    coatOfArms: apiCountry.coatOfArms ?? { png: '', svg: '' },
    startOfWeek: apiCountry.startOfWeek ?? '',
    capitalInfo: apiCountry.capitalInfo ?? { latlng: [] },
    postalCode: apiCountry.postalCode ?? { format: '', regex: '' },
  };
}
