import { CountryByCode } from '@interfaces/country-by-code';
import { Country } from '@interfaces/country';

export function normalizeCountry(apiCountry: any): Country {
  return {
    name: {
      common: apiCountry.name?.common ?? '',
      official: apiCountry.name?.official ?? '',
      nativeName: apiCountry.name?.nativeName ?? {},
    },
    tld: apiCountry.tld,
    cca2: apiCountry.cca2,
    ccn3: apiCountry.ccn3,
    cioc: apiCountry.cioc,
    independent: apiCountry.independent ?? false,
    status: apiCountry.status,
    unMember: apiCountry.unMember,
    currencies: apiCountry.currencies ?? {},
    idd: apiCountry.idd ?? { root: '', suffixes: [] },
    capital: apiCountry.capital ?? [],
    altSpellings: apiCountry.altSpellings ?? [],
    region: apiCountry.region,
    subregion: apiCountry.subregion,
    languages: apiCountry.languages ?? {},
    latlng: apiCountry.latlng ?? [],
    landlocked: apiCountry.landlocked ?? false,
    borders: apiCountry.borders ?? [],
    area: apiCountry.area,
    demonyms: apiCountry.demonyms ?? { eng: { f: '', m: '' }, fra: { f: '', m: '' } },
    cca3: apiCountry.cca3,
    translations: apiCountry.translations ?? {},
    flag: apiCountry.flag ?? '',
    maps: apiCountry.maps ?? { googleMaps: '', openStreetMaps: '' },
    population: apiCountry.population,
    gini: apiCountry.gini ?? {},
    fifa: apiCountry.fifa,
    car: apiCountry.car ?? { signs: [], side: '' },
    timezones: apiCountry.timezones ?? [],
    continents: apiCountry.continents ?? [],
    flags: apiCountry.flags ?? { png: '', svg: '', alt: '' },
    coatOfArms: apiCountry.coatOfArms ?? { png: '', svg: '' },
    startOfWeek: apiCountry.startOfWeek ?? '',
    capitalInfo: apiCountry.capitalInfo ?? { latlng: [] },
    postalCode: apiCountry.postalCode ?? { format: '', regex: '' },
  };
}

export function normalizeCountryData(data: any): CountryByCode {
  return {
    name: {
      common: data.name?.common || '',
      official: data.name?.official || '',
      nativeName: {
        spa: {
          official: data.name?.nativeName?.eng?.official || '',
          common: data.name?.nativeName?.eng?.common || '',
        },
      },
    },
    tld: data.tld || [],
    cca2: data.cca2 || '',
    ccn3: data.ccn3 || '',
    cioc: data.cioc || '',
    independent: !!data.independent,
    status: data.status || '',
    unMember: !!data.unMember,
    currencies: data.currencies ?? {},
    idd: {
      root: data.idd?.root || '',
      suffixes: data.idd?.suffixes || [],
    },
    capital: data.capital || [],
    altSpellings: data.altSpellings || [],
    region: data.region || '',
    subregion: data.subregion || '',
    languages: data.languages || {},
    latlng: data.latlng || [],
    landlocked: !!data.landlocked,
    borders: data.borders || [],
    bordersWithCode: [],
    area: data.area || 0,
    demonyms: {
      eng: {
        f: data.demonyms?.eng?.f || '',
        m: data.demonyms?.eng?.m || '',
      },
      fra: {
        f: data.demonyms?.fra?.f || '',
        m: data.demonyms?.fra?.m || '',
      },
    },
    cca3: data.cca3 || '',
    translations: {
      ara: { official: data.translations?.eng?.official || '', common: data.translations?.eng?.common || '' },
      bre: { official: '', common: '' },
      ces: { official: '', common: '' },
      cym: { official: '', common: '' },
      deu: { official: '', common: '' },
      est: { official: '', common: '' },
      fin: { official: '', common: '' },
      fra: { official: '', common: '' },
      hrv: { official: '', common: '' },
      hun: { official: '', common: '' },
      ind: { official: '', common: '' },
      ita: { official: '', common: '' },
      jpn: { official: '', common: '' },
      kor: { official: '', common: '' },
      nld: { official: '', common: '' },
      per: { official: '', common: '' },
      pol: { official: '', common: '' },
      por: { official: '', common: '' },
      rus: { official: '', common: '' },
      slk: { official: '', common: '' },
      spa: { official: '', common: '' },
      srp: { official: '', common: '' },
      swe: { official: '', common: '' },
      tur: { official: '', common: '' },
      urd: { official: '', common: '' },
      zho: { official: '', common: '' },
    },
    flag: data.flag || '',
    maps: {
      googleMaps: data.maps?.googleMaps || '',
      openStreetMaps: data.maps?.openStreetMaps || '',
    },
    population: data.population || 0,
    gini: {
      '2019': data.gini?.['2019'] || 0,
    },
    fifa: data.fifa || '',
    car: {
      signs: data.car?.signs || [],
      side: data.car?.side || '',
    },
    timezones: data.timezones || [],
    continents: data.continents || [],
    flags: {
      png: data.flags?.png || '',
      svg: data.flags?.svg || '',
      alt: data.flags?.alt || '',
    },
    coatOfArms: {
      png: data.coatOfArms?.png || '',
      svg: data.coatOfArms?.svg || '',
    },
    startOfWeek: data.startOfWeek || '',
    capitalInfo: {
      latlng: data.capitalInfo?.latlng || [],
    },
    postalCode: {
      format: data.postalCode?.format || '',
      regex: data.postalCode?.regex || '',
    },
  };
}
